<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-22T14:58:41Z" name="LoginTCSuite" finished-at="2021-02-22T14:59:27Z" duration-ms="45412">
    <groups>
    </groups>
    <test started-at="2021-02-22T14:58:41Z" name="Test" finished-at="2021-02-22T14:59:27Z" duration-ms="45412">
      <class name="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest">
        <test-method is-config="true" signature="setup(java.lang.String, java.lang.String)[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@59b98ad1]" started-at="2021-02-22T09:58:41Z" name="setup" finished-at="2021-02-22T09:59:01Z" duration-ms="20171" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC01_FailedLoginTest()[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@59b98ad1]" started-at="2021-02-22T09:59:01Z" name="TC01_FailedLoginTest" finished-at="2021-02-22T09:59:21Z" duration-ms="19812" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_FailedLoginTest -->
        <test-method signature="TC02_FailedLoginTest()[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@59b98ad1]" started-at="2021-02-22T09:59:21Z" name="TC02_FailedLoginTest" finished-at="2021-02-22T09:59:22Z" duration-ms="527" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Not matched expected [Invalid] but found [Invalid credentials]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Not matched expected [Invalid] but found [Invalid credentials]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest.TC02_FailedLoginTest(TC_LoginTest.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_FailedLoginTest -->
        <test-method signature="TC03_SuccessLoginTest()[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@59b98ad1]" started-at="2021-02-22T09:59:23Z" name="TC03_SuccessLoginTest" finished-at="2021-02-22T09:59:26Z" duration-ms="3339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_SuccessLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@59b98ad1]" started-at="2021-02-22T09:59:26Z" name="tearDown" finished-at="2021-02-22T09:59:27Z" duration-ms="664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- LoginTCSuite -->
</testng-results>
