<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KB4CSNC1" failures="1" tests="3" name="Test" time="45.412" errors="0" timestamp="22 Feb 2021 14:59:28 GMT">
  <testcase classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest" name="TC01_FailedLoginTest" time="19.812"/>
  <testcase classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest" name="TC02_FailedLoginTest" time="0.527">
    <failure type="java.lang.AssertionError" message="Not matched expected [Invalid] but found [Invalid credentials]">
      <![CDATA[java.lang.AssertionError: Not matched expected [Invalid] but found [Invalid credentials]
	at com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest.TC02_FailedLoginTest(TC_LoginTest.java:75)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- TC02_FailedLoginTest -->
  <testcase classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest" name="TC03_SuccessLoginTest" time="3.339"/>
</testsuite> <!-- Test -->
